C
*DECK VISPRERR
      SUBROUTINE VISPRERR(VISERRORNO,VISSUBNAME)
C     ******************************************************************
C     * THIS ROUTINE PRINTS ERROR MESSAGES. VISERRORNO CONTAINS THE    *
C     * NUMBER OF THE MESSAGE. VISSUBNAME CONTAINS THE NAME OF THE     *
C     * CALLING SUBROUTINE.                                            *
C     ******************************************************************
C
C#include "comerrn"
C#include "cominou"

	INCLUDE 'INCLUDE/comerrn'
	INCLUDE 'INCLUDE/cominou'


C
      CHARACTER*(*) VISSUBNAME
      INTEGER       VISERRORNO
C
      IF (VISERRORNO.EQ.VISERRAUXI) WRITE(VISSTDERRO,4)  4,VISSUBNAME
      IF (VISERRORNO.EQ.VISERRTRAN) WRITE(VISSTDERRO,5)  5,VISSUBNAME
      IF (VISERRORNO.EQ.VISERRNDIM) WRITE(VISSTDERRO,7)  7,VISSUBNAME
      IF (VISERRORNO.EQ.VISERRSERI) WRITE(VISSTDERRO,8)  8,VISSUBNAME
      IF (VISERRORNO.EQ.VISERRFIFO) WRITE(VISSTDERRO,10)  10,VISSUBNAME
      IF (VISERRORNO.EQ.VISERRTYPE) WRITE(VISSTDERRO,14)  14,VISSUBNAME
      IF (VISERRORNO.EQ.VISERRSTRU) WRITE(VISSTDERRO,15)  15,VISSUBNAME
      IF (VISERRORNO.EQ.VISERRWRST) WRITE(VISSTDERRO,21)  21,VISSUBNAME
      IF (VISERRORNO.EQ.VISERRPACK) WRITE(VISSTDERRO,22)  22,VISSUBNAME
      IF (VISERRORNO.EQ.VISERRCFLO) WRITE(VISSTDERRO,23)  23,VISSUBNAME
      IF (VISERRORNO.EQ.VISERRCXDR) WRITE(VISSTDERRO,24)  24,VISSUBNAME
      IF (VISERRORNO.EQ.VISERRIEEE) WRITE(VISSTDERRO,25)  25,VISSUBNAME
C
      WRITE(VISSTDERRO,*)
      WRITE(VISSTDERRO,'(A)') '***VISPRERR: TERMINATING DUE TO ERROR.'
C
      STOP
C
C     *FORMATS
    4 FORMAT(//I2,1X,'***',A,'*ERROR: COORDINATES FOR AUXILIARY',
     A                   ' GEOMETRY SHOULD ALWAYS BE DEFINED WITH',
     B                   ' CARTESIAN COORDINATES.')
    5 FORMAT(//I2,1X,'***',A,'*ERROR: TRANSFORMATION ONLY POSSIBLE FOR',
     A                   '  CYLINDER -> TOKAMAK AND',
     B                   '  CYLINDER -> CORONAL LOOP.')
    7 FORMAT(//I2,1X,'***',A,'*ERROR: NDIM SHOULD SATISFY:',
     A                   ' 1 <= NDIM <= 3.')
    8 FORMAT(//I2,1X,'***',A,'*ERROR: THE TIME DEPENDENCE CAN ONLY BE',
     A                   ' VISUALIZED BY MAKING VISSERIES .TRUE.',
     B                   ' IT MAY NOT APPEAR IN VISCOOR.')
   10 FORMAT(//I2,1X,'***',A,'*ERROR: WRONG FILE FORMAT INDICATION. IT',
     A                   ' SHOULD EQUAL VISGENERAL OR VISINTERNA.')
   14 FORMAT(//I2,1X,'***',A,'*ERROR: WRONG PRIMITIVE TYPE')
   15 FORMAT(//I2,1X,'***',A,'*ERROR: ALL THE DATA STRUCTURES AT A',
     A                   ' NODE SHOULD HAVE THE SAME PRIMITIVE DATA',
     B                   ' TYPE.')
   21 FORMAT(//I2,1X,'***',A,'*ERROR: LOVER ONLY SUPPORTS THE SCALAR',
     A                   ' FIELD STRUCTURE (VISRANKSCA) AND THE',
     B                   ' 1-VECTOR, 2-VECTOR, AND 3-VECTOR',/,
     B               11X,' FIELD STRUCTURE (VISRANKVC1,2,3).')
   22 FORMAT(//I2,1X,'***',A,'*ERROR: INPUT PARAMETER VISPACKAGE MUST',
     A                   ' EQUAL ''A'' FOR AVS OR ''D'' FOR DX.')
   23 FORMAT(//I2,1X,'***',A,'*ERROR: ONLY LOVER TYPE DOUBLE (= CRAY',
     A                   ' TYPE FLOAT) SUPPORTED.')
   24 FORMAT(//I2,1X,'***',A,'*ERROR: CURRENTLY, XDR ONLY SUPPORTED ON',
     A                   ' CRAY.')
   25 FORMAT(//I2,1X,'***',A,'*ERROR: OVERFLOWS DETECTED IN CALL TO',
     A                   ' CRAY2IEG.')
      END
