function [tree] = sci_read_transform_par(tree)
// Generated by M2SCI
// Conversion function for Matlab read_transform_par
// Input: tree = Matlab funcall tree
// Ouput: tree = Scilab equivalent for tree

tree=Funcall("exec",1,Rhs_tlist(tree.name),tree.lhs)
endfunction
