function [tree] = sci_getlog(tree)
// Generated by M2SCI
// Conversion function for Matlab getlog
// Input: tree = Matlab funcall tree
// Ouput: tree = Scilab equivalent for tree

tree=Funcall("exec",1,Rhs_tlist(tree.name),tree.lhs)
endfunction
