function [tree] = sci_dispnum(tree)
// Copyright INRIA (Generated by M2SCI)
// Conversion function for Matlab dispnum()
// Input: tree = Matlab funcall tree
// Ouput: tree = Scilab equivalent for tree
endfunction
